def serial_num_to_sc(serial_number):
    sc, bay = 'null', 'null'
    if serial_number == 'FM209':  sc,bay = 'mms1', 'des0'
    if serial_number == 'FM211':  sc,bay = 'mms1', 'des1'
    if serial_number == 'FM212':  sc,bay = 'mms1', 'des2'
    if serial_number == 'FM207':  sc,bay = 'mms1', 'des3'
    if serial_number == 'FM203':  sc,bay = 'mms2', 'des0'
    if serial_number == 'FM204':  sc,bay = 'mms2', 'des1'        
    if serial_number == 'FM201':  sc,bay = 'mms2', 'des2'
    if serial_number == 'FM202':  sc,bay = 'mms2', 'des3'
    if serial_number == 'FM206':  sc,bay = 'mms3', 'des0'
    if serial_number == 'FM216':  sc,bay = 'mms3', 'des1'
    if serial_number == 'FM213':  sc,bay = 'mms3', 'des2'
    if serial_number == 'FM214':  sc,bay = 'mms3', 'des3'
    if serial_number == 'FM215':  sc,bay = 'mms4', 'des0'
    if serial_number == 'FM210':  sc,bay = 'mms4', 'des1'
    if serial_number == 'FM208':  sc,bay = 'mms4', 'des2'
    if serial_number == 'FM205':  sc,bay = 'mms4', 'des3'        

    if serial_number == 'FM002':  sc,bay = 'mms1', 'dis0'
    if serial_number == 'FM005':  sc,bay = 'mms1', 'dis1'
    if serial_number == 'FM006':  sc,bay = 'mms1', 'dis2'
    if serial_number == 'FM013':  sc,bay = 'mms1', 'dis3'
    if serial_number == 'FM014':  sc,bay = 'mms2', 'dis0'
    if serial_number == 'FM001':  sc,bay = 'mms2', 'dis1'        
    if serial_number == 'FM009':  sc,bay = 'mms2', 'dis2'
    if serial_number == 'FM012':  sc,bay = 'mms2', 'dis3'
    if serial_number == 'FM008':  sc,bay = 'mms3', 'dis0'
    if serial_number == 'FM015':  sc,bay = 'mms3', 'dis1'
    if serial_number == 'FM016':  sc,bay = 'mms3', 'dis2'
    if serial_number == 'FM007':  sc,bay = 'mms3', 'dis3'
    if serial_number == 'FM010':  sc,bay = 'mms4', 'dis0'
    if serial_number == 'FM011':  sc,bay = 'mms4', 'dis1'
    if serial_number == 'FM003':  sc,bay = 'mms4', 'dis2'
    if serial_number == 'FM004':  sc,bay = 'mms4', 'dis3'
        
    return sc, bay